version: '1.0'
stages:
  - git
  - testrepo
  - build
  - testimage
  - test

steps:
  CloneRepo:
    title: Cloning the GIT repo
    stage: git
    type: git-clone
    repo: 'ParagWankhade/node_db_connect'
  
  #TestRepo:
  #  title: test repo
  #  stage: testrepo
  #  image: alpine
  #  commands:
  #    - cd node_db_connect
  #   - ls -a

  BuildMongo:
    title: Build mongo image
    stage: build
    type: build
    working_directory: ${{CloneRepo}}/Docker/mongo
    dockerfile: Dockerfile
    image_name: build-mongo
    tag: "1"
    build_arguments: ["--replSet", "rs0", "--bind_ip_all"]


  #BuildNode:
  #  title: Build node image
  # stage: build
  #  type: build
  #  working_directory: ${{CloneRepo}}
  #  dockerfile: Docker/node/Dockerfile
   # image_name: build-node
   # tag: "1"

  TestMongoImage:    
    title: Build mongo image
    stage: testimage
    type: freestyle
    image: alpine
    commands:
      - cat /node_db_connect/compose.yaml
      #- mongo --host rs0/localhost:27017 --eval 'rs.initiate()'

  #TestNodeImage:    
  #  title: Build node image
  #  stage: testimage
  #  type: freestyle
  #  environment:
  #    - MONGO_URL = localhost
  #  image: ${{BuildNode}}
  # commands:
  #    - cd node_db_connect
  #    - ls
  #    #- node index.js
  

  my_integration_tests:
    image: mongo
    title: "Integration tests"
    stage: test
    type: composition
    composition: ../node_db_connect/compose.yaml
    composition_candidates:
      my_test_service:
        image: python
        working_dir: /root
        command: 'pwd'


