version: '1.0'
stages:
  - git
  - testrepo
  - build
  - test

steps:
  CloneRepo:
    title: Cloning the GIT repo
    stage: git
    type: git-clone
    repo: 'ParagWankhade/node_db_connect'
  
  TestRepo:
    title: test repo
    stage: testrepo
    image: alpine
    commands:
      - cd node_db_connect
      - ls -a

