version: '1.0'
stages:
  - git
  - testrepo
  - build
  - testimage
  - test

steps:
  CloneRepo:
    title: Cloning the GIT repo
    stage: git
    type: git-clone
    repo: 'ParagWankhade/node_db_connect'
  
  TestRepo:
    title: test repo
    stage: testrepo
    image: alpine
    commands:
      - cd node_db_connect
      - ls -a

  BuildMongo:
    title: Build mongo image
    stage: build
    type: build
    dockerfile: Docker/mongo
    image_name: build-mongo
    tag: 1


  BuildNode:
    title: Build node image
    stage: build
    type: build
    dockerfile: Docker/node
    image_name: build-node
    tag: 1

  TestMongoImage:    
    title: Build mongo image
    stage: build
    type: freestyle
    image: ${{BuildMongo}}
    commands:
      - cat /etc/mongod.conf.orig

  TestNodeImage:    
    title: Build mongo image
    stage: build
    type: freestyle
    image: ${{BuildNode}}
    commands:
      - ls
  

