version: '1.0'
stages:
  - git
  - testrepo
  - build
  - testimage
  - test

steps:
  CloneRepo:
    title: Cloning the GIT repo
    stage: git
    type: git-clone
    repo: 'ParagWankhade/node_db_connect'
  
  #TestRepo:
  #  title: test repo
  #  stage: testrepo
  #  image: alpine
  #  commands:
  #    - cd node_db_connect
  #   - ls -a

  BuildMongo:
    title: Build mongo image
    stage: build
    type: build
    working_directory: ${{CloneRepo}}/Docker/mongo
    dockerfile: Dockerfile
    image_name: build-mongo
    tag: "1"
    build_arguments: ["--replSet", "rs0", "--bind_ip_all"]


  #BuildNode:
  #  title: Build node image
  # stage: build
  #  type: build
  #  working_directory: ${{CloneRepo}}
  #  dockerfile: Docker/node/Dockerfile
   # image_name: build-node
   # tag: "1"

  TestMongoImage:    
    title: Build mongo image
    stage: testimage
    type: freestyle
    image: ${{BuildMongo}}
    commands:
      - cat /etc/mongod.conf.orig
      #- mongo --host rs0/localhost:27017 --eval 'rs.initiate()'

  #TestNodeImage:    
  #  title: Build node image
  #  stage: testimage
  #  type: freestyle
  #  environment:
  #    - MONGO_URL = localhost
  #  image: ${{BuildNode}}
  # commands:
  #    - cd node_db_connect
  #    - ls
  #    #- node index.js
  

  my_integration_tests:
    image: mongo
    title: "Integration tests"
    stage: test
    type: composition
    composition: 
      version: '3.7'
      services:
          mongo1:
              hostname: mongo1
              container_name: gogqlserver_mongo1
              image: mongo
              expose:
                  - 27017
              ports:
                  - 27017:27017
              entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
              depends_on:
                - mongo2
              
          mongo2:
              hostname: mongo2
              container_name: gogqlserver_mongo2
              image: mongo
              expose:
                  - 27017
              ports:
                  - 27018:27017
              entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

          mongo-express:
              container_name: gogqlserver_mongo_express
              image: mongo
              ports:
                  - 8081:8081        
              commands:
                - sleep 30
                - mongo mongodb://mongo1:27017/ --eval "rs.initiate({_id:'rs0'})"
                - sleep 20 && echo "1"
                - mongo mongodb://mongo1:27017/ --eval "rs.add({host:'mongo2:27017', priority:0, votes:0})"
                - sleep 20 && echo "2"
                - mongo mongodb://mongo1:27017/ --eval "rs.status()"
                - mongo --host rs0/mongo1:27017
              depends_on:
                - mongo1
                - mongo2
    composition_candidates:
      my_test_service:
        image: python
        working_dir: /root
        command: 'pwd'


