version: '1.0'
stages:
  - git
  - testrepo
  - build
  - testimage
  - test

steps:
  CloneRepo:
    title: Cloning the GIT repo
    stage: git
    type: git-clone
    repo: 'ParagWankhade/node_db_connect'
  
  TestRepo:
    title: test repo
    stage: testrepo
    image: alpine
    commands:
      - cd node_db_connect
      - ls -a

  BuildMongo:
    title: Build mongo image
    stage: build
    type: build
    working_directory: ${{CloneRepo}}/Docker/mongo
    dockerfile: Dockerfile
    image_name: build-mongo
    tag: "1"


  BuildNode:
    title: Build node image
    stage: build
    type: build
    working_directory: ${{CloneRepo}}
    dockerfile: Docker/node/Dockerfile
    image_name: build-node
    tag: "1"

  TestMongoImage:    
    title: Build mongo image
    stage: testimage
    type: freestyle
    image: ${{BuildMongo}}
    commands:
      - cat /etc/mongod.conf.orig

  TestNodeImage:    
    title: Build node image
    stage: testimage
    type: freestyle
    environment:
      - MONGO_URL = localhost
    image: ${{BuildNode}}
    commands:
      - cd node_db_connect
      - ls
      #- node index.js
  

  my_integration_tests:
    image: mongo
    title: "Integration tests"
    stage: test
    environment:
      - MONGO_URL= my_mongo_Service
    commands:
      - mongo mongodb://my_mongo_Service:27017/mydb
      #?replicaSet=rs0
      #- cd node_db_connect
      #- npm install
      #- node index.js
    services:
      composition:
        my_mongo_Service:
          image: ${{BuildMongo}}        
          command: ["ls -lR"]
            #["mongod","--config", "./mongodb_replica_sets/configs/mongod_1.conf"]

