services: 
  mongo1: 
    container_name: gogqlserver_mongo1
    depends_on: 
      - mongo2
    entrypoint: 
      - /usr/bin/mongod
      - "--bind_ip_all"
      - "--replSet"
      - rs0
    expose: 
      - 27017
    hostname: mongo1
    image: mongo
  mongo2: 
    container_name: gogqlserver_mongo2
    entrypoint: 
      - /usr/bin/mongod
      - "--bind_ip_all"
      - "--replSet"
      - rs0
    expose: 
      - 27017
    hostname: mongo2
    image: mongo
version: "3"