services: 
  mongo-express: 
    commands: 
      - "sleep 30"
      - "mongo mongodb://mongo1:27017/ --eval \"rs.initiate({_id:'rs0'})\""
      - "sleep 20 && echo \"1\""
      - "mongo mongodb://mongo1:27017/ --eval \"rs.add({host:'mongo2:27017', priority:0, votes:0})\""
      - "sleep 20 && echo \"2\""
      - "mongo mongodb://mongo1:27017/ --eval \"rs.status()\""
      - "mongo --host rs0/mongo1:27017"
    container_name: gogqlserver_mongo_express
    depends_on: 
      - mongo1
      - mongo2
    image: mongo
    ports: 
      - "8081:8081"
  mongo1: 
    container_name: gogqlserver_mongo1
    depends_on: 
      - mongo2
    entrypoint: 
      - /usr/bin/mongod
      - "--bind_ip_all"
      - "--replSet"
      - rs0
    expose: 
      - 27017
    hostname: mongo1
    image: mongo
    ports: 
      - "27017:27017"
  mongo2: 
    container_name: gogqlserver_mongo2
    entrypoint: 
      - /usr/bin/mongod
      - "--bind_ip_all"
      - "--replSet"
      - rs0
    expose: 
      - 27017
    hostname: mongo2
    image: mongo
    ports: 
      - "27018:27017"
version: "3"